### ISSUE TITLE
API endpoint hardcoded for GitHub.com and doesn't support GHES/GHAE

### ISSUE THREAD

**Issue by anweiss** [GeekMasher/advanced-security-compliance#30]
**Describe the bug**

The API endpoint that is formed at https://github.com/GeekMasher/advanced-security-compliance/blob/main/ghascompliance/octokit/octokit.py#L41 is hardcoded for GitHub.com. However, GitHub Enterprise Server (GHES) and GitHub AE (GHAE) use the /api/graphql endpoint route for the GraphQL API.

**To Reproduce**

1. Set the `--github-instance` flag to either a GHES or GHAE instance
2. Run the action

**Expected behavior**

Action works as advertised.

**Screenshots**

**Desktop (please complete the following information):**

N/A

**Smartphone (please complete the following information):**

N/A

**Additional context**

N/A

**Comment by GeekMasher** [comment]
Created a patch https://github.com/GeekMasher/advanced-security-compliance/commit/84eb633d3be2a7572a8bbca75846612e186c8dda

Please test it out and see if it solved the issue before I merge and created a release.

**Comment by GeekMasher** [comment]
Fixed with the [v1.5 release](https://github.com/GeekMasher/advanced-security-compliance/releases/tag/v1.5)
