### ISSUE TITLE
Code scanning fails even if there's a fix for an alert in the current branch

### ISSUE THREAD

**Issue by oliveiraleom** [GeekMasher/advanced-security-compliance#33]
**Describe the bug**
Code scanning fails for new branch when there's an alert for master branch. The fix for the alert is in the new branch.

**To Reproduce**
1. Hard code a password in master and run  the action against it. It will generate a code scanning alert
2. Open a pull request with a fix for the hard coded password
3. Action will fail in the new pull request even if there's a fix for the issue in there

**Expected behavior**
Action should succeed in the new pull request as there's a fix for the code scanning alert

**Screenshots**
Error in master:
<img width="491" alt="001" src="https://user-images.githubusercontent.com/57901537/130953553-5647f469-782e-4c2d-87c0-7f63ea7ecaca.PNG">

Just master is an option here:
<img width="535" alt="002" src="https://user-images.githubusercontent.com/57901537/130953657-ebc47ea5-28e1-43b3-b68a-010e2de757c3.PNG">

Action still fails in fix pull request :
<img width="548" alt="003" src="https://user-images.githubusercontent.com/57901537/130953774-f21614f0-737a-43ea-8bf2-6d9f5abfa05a.PNG">

Change that fixes the issue:
<img width="461" alt="004" src="https://user-images.githubusercontent.com/57901537/130953971-63b196f6-c30e-47a8-ae46-c2485277509c.PNG">

**Comment by GeekMasher** [comment]
@oliveiraleom This issue is being closed and more to the new repo under another issue https://github.com/advanced-security/policy-as-code/issues/2
