### ISSUE TITLE
Severity `note` not recognized

### ISSUE THREAD

**Issue by aleks-ivanov** [GeekMasher/advanced-security-compliance#39]
**Describe the bug**
There is a code scanning severity called `note` and currently the action doesn't recognize it.

`Warning:  Unknown Severity used - note`

**To Reproduce**
1. Fork [this repo](https://github.com/restsharp/RestSharp)
2. Run CodeQL with security-and-quality queries to get `note` alerts
3. Run GHASC action with `severity: notes`

**Expected behavior**
Seems that it should detect the `note` severity.

**Comment by GeekMasher** [comment]
@aleks-ivanov Very good catch and I must have missed it, I have approved your PR and merged. I have an issue with the Action workflow but should be fixed now in main. Creating an updated version today.
