### ISSUE TITLE
Documentation - Using GitHub App with Action

### ISSUE THREAD

**Issue by GeekMasher** [GeekMasher/advanced-security-compliance#54]
### Description

We need some introductional docs on how to setup and use this Action using a GitHub App.

**Related:**
- #50
  - #51 

+cc @4bg0P 

### Propose Solution

- [ ] New Document
- [ ] Reasoning for using GitHub App versus a PAT
- [ ] Full example workflow
    - Using [peter-murray/workflow-application-token-action](https://github.com/peter-murray/workflow-application-token-action)?

**Comment by angusjellis** [comment]
Hi @GeekMasher, where within the 'docs' folder are you expecting this to live? I managed to get authentication with a GitHub app working recently using V1.6.3 of your action 🎊

**Comment by GeekMasher** [comment]
@angusjellis Just seen this comment and PR ❤️ Let me review it today or next week and hopefully get it merged soon

**Comment by PeterMerkert** [comment]
To be honest, maybe you can also just embed this video from a coworker of yours: https://youtu.be/1MhmeuaaqRY?t=496 
This is how I got into this repository.
