### ISSUE TITLE
Policy file not found

### ISSUE THREAD

**Issue by jeffpaul** [GeekMasher/advanced-security-compliance#60]
**Describe the bug**
I've got a sample license and policy file in a repo (see this [current PR](https://github.com/10up/insert-special-characters/pull/122)), but the [action run is saying the repo can not be cloned](https://github.com/10up/insert-special-characters/runs/6025938094?check_suite_focus=true).  I'm trying to test this in a single repo in our org to validate that we can scan for licensing issues in dependencies, assuming I can get this to work in a single repo then I would likely move the policy file to our org's `.github` repo and reference that policy file in other repos but for now have the policy file in the same repo where the licensing action is running.  Problem is I'm not sure if I'm referencing the policy file correctly or not.  Also not sure after reading the auth docs if we've got a Personal Access Token set up correctly for the `ACCESS_TOKEN` in the action.  So I'm hoping you can take a look at our PR and failed action run to recommend any changes to the licensing action, the policy file and its location, or our access token set up.  Once we get it triaged, I'd be happy to help with a PR here to add to the docs for places where I got tripped up.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by GeekMasher** [comment]
Talked in https://github.com/10up/insert-special-characters/pull/122, closing issues now
