### ISSUE TITLE
Dependabot not supporting GitHub Enterprise

### ISSUE THREAD

**Issue by midwestKC-coder** [GeekMasher/advanced-security-compliance#65]
**Describe the bug**
The change to support GitHub enterprise missed changing dependabot.py.  It is still using direct GitHub cloud reference:
        instance = "https://api.github.com/graphql"

**To Reproduce**
1. Code inspection
dependabot.py
Line 80 -  instance = "https://api.github.com/graphql"

**Expected behavior**
Dependabot should use the GitHub enterprise URL and not the GitHub Cloud URL

This change was missed with the merge (https://github.com/GeekMasher/advanced-security-compliance/pull/31) that added support for GitHub Enterprise.

**Comment by GeekMasher** [comment]
@midwestKC-coder You are absolutely right and this needs to be fixed.

I have the [GHES instance info already present](https://github.com/GeekMasher/advanced-security-compliance/blob/main/ghascompliance/octokit/octokit.py#L51) in the tool but dependabot isn't use it.

The main issue is on lines:
- [dependabot.py#L103](https://github.com/GeekMasher/advanced-security-compliance/blob/main/ghascompliance/octokit/dependabot.py#L103)
- [dependabot.py#L144](https://github.com/GeekMasher/advanced-security-compliance/blob/main/ghascompliance/octokit/dependabot.py#L144)

**Comment by GeekMasher** [comment]
@midwestKC-coder The patch is done. I even wrote a while ago the [tests for this exact use-case](https://github.com/GeekMasher/advanced-security-compliance/blob/main/tests/test_octokit.py#L22-L29) but forgot to implement it for Dependabot.
