### ISSUE TITLE
GitHub Enterprise seems to not support ...

### ISSUE THREAD

**Issue by midwestKC-coder** [GeekMasher/advanced-security-compliance#67]
**Describe the bug**
We have updated to the v1.6.3.  
This newer version gives the following error
"message": "Field 'dependencyGraphManifests' doesn't exist on type 'Repository'"

We used the following command line options to disable licensing ( --disable-dependency-licensing --disable-dependencies) and got the same error.

We grabbed the GraphQL GRAPHQL_DEPENDENCY_INFO from dependency.py and got the same error calling the GraphQL API directly.

We compared the GitHub Cloud API (https://docs.github.com/en/graphql/overview/schema-previews) with the GitHut Enterprise API (https://docs.github.com/en/enterprise-server@3.6/graphql/overview/schema-previews).

GitHub Cloud API has a section called 'Access to a repositories dependency graph preview'.
GitHub Enterprise API does NOT have this section.

Are we correct in assuming this functionality has not been released for GitHub Enterprise yet?

Is this functionality required for dependabot policy functionality?
If it is, which GitHub Enterprise version will support 'Access to a repositories dependency graph preview'?

**To Reproduce**
1. Run action with dependabot enabled on GitHub Enterprise @3.6.2

**Expected behavior**
Dependabot policy functionality works as it already does on GitHub Cloud

**Comment by GeekMasher** [comment]
@midwestKC-coder Thanks for sharing this, let me do some investigation around this before I give an answer to your question

**Comment by GeekMasher** [comment]
@midwestKC-coder You are absolutely right. I had a chat with the Product Management team and they are looking into providing this API for GHES users.

**Comment by GeekMasher** [comment]
@midwestKC-coder This issue will be fixed in an up coming GHES release
