### ISSUE TITLE
Change "conditions" for a more meaningful name

### ISSUE THREAD

**Issue by jmservera** [GeekMasher/advanced-security-compliance#71]
### Description

As a noob I find confusing the term "conditions" because I don't know if it is a condition to fail or to pass.

### Propose Solution

Instead of "ignore" and "conditions", can we find something that clearly states what will happen like allow/disallow or similar?
I understand this will cause a compatibility issue with existing license policies, but you could warn that there will be a breaking change during a time window to allow everyone to change it.

@romanoroth, @Padi-owasp

**Comment by GeekMasher** [comment]
@jmservera You are absolutely right. The terms I used are not great and I think they need to be easier to understand.

This is something I want for v2 of this Action. 

**For reference:**

- Warnings (match == warning in the console, continues)
- Ignores (match == skips and does not break)
- Conditions (match == break)

**Comment by GeekMasher** [comment]
@jmservera Closing issue, please raise all new ones in the new repo
https://github.com/advanced-security/policy-as-code/issues
